
services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - env/mysql.env
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql # Указываем, что phpMyAdmin зависит от MySQL
    environment:
      PMA_HOST: mysql # Имя сервиса MySQL (должно совпадать с названием в docker-compose)
      PMA_USER: root # Тот же пользователь, что в MySQL
      PMA_PASSWORD: "" # Пароль MySQL
    ports:
      - "8080:80" # Открываем phpMyAdmin на порту 8080
  queue:
    build:
      context: dockerfiles
      dockerfile: cron.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    working_dir: /var/www/laravel
    depends_on:
      - mysql
    command: php artisan queue:work --daemon


  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel

  # artisan:
  #   build:
  #     context: dockerfiles
  #     dockerfile: php.Dockerfile
  #   volumes:
  #     - ./src:/var/www/laravel
  #   entrypoint: ["php", "/var/www/laravel/artisan"]